INFO - 2023-12-13 12:34:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:41:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-12-13 12:45:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-12-13 12:48:03 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'projetoweb', 3346, '', 0)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM a...')
#4 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(NULL)
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#7 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM a...')
#3 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(NULL)
#4 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-13 12:48:03 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM atendimento WHERE CodAnimal LIKE \'%\'')
 3 APPPATH\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(null)
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-13 12:50:58 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'projetoweb', 3346, '', 0)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM a...')
#4 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(NULL)
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#7 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM a...')
#3 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(NULL)
#4 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-13 12:50:58 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Banco_Query.php(99): CodeIgniter\Database\BaseConnection->query('SELECT * FROM atendimento WHERE CodAnimal LIKE \'%\'')
 3 APPPATH\Controllers\Dados.php(442): App\Models\Banco_Query->consultaAtendimento(null)
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dados->consultaAtendimento()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-13 12:56:00 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'projetoweb', 3346, '', 0)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(NULL)
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#7 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(NULL)
#4 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-13 12:56:00 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM cliente WHERE Nome LIKE \'%\'')
 3 APPPATH\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(null)
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-13 13:01:29 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'projetoweb', 3346, '', 0)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#4 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(NULL)
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#7 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\PetSystem\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\PetSystem\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\PetSystem\app\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM c...')
#3 C:\xampp\htdocs\PetSystem\app\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(NULL)
#4 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
#5 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
#6 C:\xampp\htdocs\PetSystem\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\PetSystem\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-12-13 13:01:29 --> Unable to connect to the database.
Main connection [MySQLi]: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Models\Banco_Query.php(52): CodeIgniter\Database\BaseConnection->query('SELECT * FROM cliente WHERE Nome LIKE \'%\'')
 3 APPPATH\Controllers\Dados.php(313): App\Models\Banco_Query->consultaCli(null)
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Dados->consultaCli()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Dados))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-12-13 13:01:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
